### ISSUE TITLE
majority mode in utils/utils_insightface.py fails 

### ISSUE THREAD

**Issue by Anurag14** [Anurag14/accessfaceid#28]
statistics. Statistics Error: no unique mode; found 2 equally common values error

**Comment by Anurag14** [comment]
(opencv-env) F:\RBS FaceReid\accessfaceid>python livestream/newmain.py
2019-05-23 12:23:17.218120: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
[LOG] Loading Encoded faces Database ...
[Camera Server] Camera is initializing ...
[FaceTracker Server] Found 1 faces!
[Base Server] Running inference...
[Live Streaming] -----------------------------------------------------------
[FaceTracker Server] Found 2 faces!
[Base Server] Running inference...
[Base Server] Running inference...
[Live Streaming] -----------------------------------------------------------
[FaceTracker Server] Found 1 faces!
[Base Server] Running inference...
[Live Streaming] -----------------------------------------------------------
[FaceTracker Server] Found 1 faces!
[Base Server] Running inference...
[Live Streaming] -----------------------------------------------------------
[FaceTracker Server] Found 1 faces!
[Base Server] Running inference...
[Live Streaming] -----------------------------------------------------------
[FaceTracker Server] Found 1 faces!
[Base Server] Running inference...
[Live Streaming] -----------------------------------------------------------
[FaceTracker Server] Found 1 faces!
[Base Server] Running inference...
[Live Streaming] -----------------------------------------------------------
[FaceTracker Server] Found 1 faces!
[Base Server] Running inference...
[Live Streaming] -----------------------------------------------------------
[FaceTracker Server] Found 1 faces!
[Base Server] Running inference...
[Live Streaming] -----------------------------------------------------------
[FaceTracker Server] Found 1 faces!
[Base Server] Running inference...
[Live Streaming] -----------------------------------------------------------
[FaceTracker Server] Found 1 faces!
[Base Server] Running inference...
Traceback (most recent call last):
  File "livestream/newmain.py", line 79, in <module>
    livestream.run()
  File ".\modules\camera_server.py", line 40, in run
    self.processs(frame)
  File "livestream/newmain.py", line 53, in processs
    _similar_face_name = self.face_db.who_is_this_face(_face_description)
  File ".\modules\face_db.py", line 54, in who_is_this_face
    who_is_this = compare_faces(self.faces_descriptions, self.faces_names, face_description, mode)
  File ".\utils\utils_insightface.py", line 57, in compare_faces
    name = face_distance_single_majority(known_face_encodings, names, face_query)
  File ".\utils\utils_insightface.py", line 19, in face_distance_single_majority
    name = mode(names[similar_indices])
  File "C:\Users\anurag singh\AppData\Local\conda\conda\envs\opencv-env\lib\statistics.py", line 507, in mode
    'no unique mode; found %d equally common values' % len(table)
statistics.StatisticsError: no unique mode; found 2 equally common values
[ WARN:0] terminating async callback

**Comment by Anurag14** [comment]
Pull request #46 solves the issue. Closing this for now
