### ISSUE TITLE
register/register.py fails after adding a unknown person 

### ISSUE THREAD

**Issue by Anurag14** [Anurag14/accessfaceid#34]
Traceback (most recent call last):
  File "register/register.py", line 79, in <module>
    register.run()
  File ".\modules\camera_server.py", line 40, in run
    self.processs(frame)
  File "register/register.py", line 58, in processs
    _similar_face_name = self.face_db.who_is_this_face(_face_description, cores='single')
  File ".\modules\face_db.py", line 54, in who_is_this_face
    who_is_this = compare_faces(self.faces_descriptions, self.faces_names, face_description)
  File ".\utils\utils_insightface.py", line 57, in compare_faces
    face_value,name= face_distance(known_face_encodings, names, face_query)
  File ".\utils\utils_insightface.py", line 11, in face_distance
    face_dist_value = np.linalg.norm(face_encodings - face_query, axis=1)
ValueError: operands could not be broadcast together with shapes (16384,) (512,)
[ WARN:0] terminating async callback

**Comment by Anurag14** [comment]
Closing the issue as this has been fixed in pull request #35
