### ISSUE TITLE
Tracker has no visualization for no faces in start. Also fails in first face visualization

### ISSUE THREAD

**Issue by Anurag14** [Anurag14/accessfaceid#37]
(opencv-env) F:\RBS FaceReid\accessfaceid>python livestream/newmain.py
2019-05-21 12:13:52.029104: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
[LOG] Loading Encoded faces Database ...
[Camera Server] Camera is initializing ...
[FaceTracker Server] Found 0 faces!
[FaceTracker Server] Found 0 faces!
[FaceTracker Server] Found 0 faces!
[FaceTracker Server] Found 0 faces!
[FaceTracker Server] Found 0 faces!
[FaceTracker Server] Found 0 faces!
[FaceTracker Server] Found 0 faces!
[FaceTracker Server] Found 0 faces!
[FaceTracker Server] Found 0 faces!
[FaceTracker Server] Found 0 faces!
[FaceTracker Server] Found 0 faces!
[FaceTracker Server] Found 0 faces!
[FaceTracker Server] Found 0 faces!
[FaceTracker Server] Found 0 faces!
[FaceTracker Server] Found 0 faces!
[FaceTracker Server] Found 0 faces!
[FaceTracker Server] Found 0 faces!
[FaceTracker Server] Found 0 faces!
[FaceTracker Server] Found 0 faces!
[FaceTracker Server] Found 0 faces!
[FaceTracker Server] Found 0 faces!
[FaceTracker Server] Found 0 faces!
[FaceTracker Server] Found 0 faces!
[FaceTracker Server] Found 0 faces!
[FaceTracker Server] Found 1 faces!
[Base Server] Running inference...
Traceback (most recent call last):
  File "livestream/newmain.py", line 74, in <module>
    demo.run()
  File ".\modules\camera_server.py", line 40, in run
    self.processs(frame)
  File "livestream/newmain.py", line 51, in processs
    _similar_face_name = self.face_db.get_similar_faces(_face_description)
  File ".\modules\face_db.py", line 37, in get_similar_faces
    print('[Face DB] Looking for similar faces in a DataBase of {} faces...'.format(len(self.faces)))
AttributeError: 'Model' object has no attribute 'faces'
[ WARN:1] terminating async callback

**Comment by Anurag14** [comment]
the demo run fix is #38
